### ISSUE TITLE
SQL error for "article activ/inactive"

### ISSUE THREAD

**Issue by chriwo** [job963/oxProbs#20]
Line 920 and line 923 in oxprobs_articles.php must be changed to:
$sWhereActive = "AND a.oxactive = 1 ";
and 
$sWhereActive = "AND a.oxactive = 0 ";

In line 930 a.oxactive = "$iActValue" must be removed, as it comes from line 920 or 923

**Comment by job963** [comment]
Thanks for reporting. Bug is fixed with version 0.8.3
