### ISSUE TITLE
SQL error for orders

### ISSUE THREAD

**Issue by Alpha-Sys** [job963/oxProbs#32]
If you go to "Problemfälle" => "Bestellungen" you will get an SQL error. There is no column "oxshopid" in the table "oxorderarticles".

![oxprobs_orders](https://user-images.githubusercontent.com/2886119/27444092-8b42950a-5775-11e7-988c-38d3e8778058.png)

**Comment by Alpha-Sys** [comment]
The column in the oxorderarticles is called "oxordershopid" instead of "oxshopid"

**Comment by job963** [comment]
Fixed in release v0.9.0 (https://github.com/job963/oxProbs/releases/tag/v0.9.0)
